import os

TELEGRAM_SECRET_URL = os.environ['TELEGRAM_SECRET_URL']
TELEGRAM_GIST_BOT_TOKEN = os.environ['TELEGRAM_GIST_BOT_TOKEN']
FILESIZE_LIMIT_IN_BYTES = 1024 * 16
GITHUB_API_URL = 'https://api.github.com/gists'
